# Generated by Django 4.2a1 on 2023-02-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0002_anime'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='link',
            field=models.URLField(default='exit', max_length=250),
            preserve_default=False,
        ),
    ]
