# Generated by Django 4.2a1 on 2023-02-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0004_anime_manga_alter_anime_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
