# Generated by Django 4.2a1 on 2023-02-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0006_anime_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mangafiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='files',
            field=models.ManyToManyField(to='manga.mangafiles'),
        ),
    ]
